logger_folder: xxp_agent_logs/automl_wrong_implementation
model: gpt-4-0125-preview
specification_type: xxp
specification_folder: examples/automl_wrong_implementation/1_separate_files
main_workflow_name: FailurePredictionInManufacture
main_workflow_package: automl_ideko
