logger_folder: xxp_agent_logs/automl_wrong_implementation
model: gpt-4o-2024-05-13
specification_type: xxp_assembled
prompt_kwargs:
  with_subworkflows: false
specification_folder: examples/automl_wrong_implementation/3_expanded
main_workflow_name: FailurePredictionInManufacture
all_xxp: true
