logger_folder: xxp_agent_logs/automl_wrong_implementation
model: gpt-4o-2024-05-13
specification_type: xxp
specification_folder: examples/automl_wrong_implementation/4_separate_files_descriptions
main_workflow_name: FailurePredictionInManufacture
main_workflow_package: automl_ideko
