logger_folder: abc_agent_logs/artificial_workflow
model: gpt-4-0125-preview
specification_type: abc
specification_folder: examples/artificial_workflow/1_separate_files
main_workflow_name: MainWorkflow
main_workflow_package: package2
