logger_folder: xxp_agent_logs/artificial_workflow
model: gpt-4o-2024-05-13
specification_type: xxp
specification_folder: examples/artificial_workflow/1_separate_files
main_workflow_name: MainWorkflow
main_workflow_package: package2
