logger_folder: xxp_agent_logs/artificial_workflow
model: gpt-4o-2024-05-13
specification_type: xxp_assembled
specification_folder: examples/artificial_workflow/2_assembled
main_workflow_name: MainWorkflow
